project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://soundaryacBU.github.io/Soundarya-Chidambaram/ 
  title: "Soundarya Chidambaram"  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Teaching.qmd
        text: Teaching
      - href: Research.qmd
        text: Research
      - href: Blog.qmd
        text: Blog      
    right:
      - icon: github
        href: https://github.com/soundaryacBU
      - href: files/CV.pdf
        text: CV
      
     
format:
  html:
    theme:
      - journal
      - brand
    css: styles.css

    include-in-header:
      - text: |
         <script data-goatcounter="https://soundaryac.goatcounter.com/count"
           async src="//gc.zgo.at/count.js"></script>
      - text: |
          <meta name="google-site-verification" content="U6OhOopcamLEMHqTQkCiPFLGp3vfHm-7gpxDDXWcAv4" />